### ISSUE TITLE
array type has incomplete element type 'struct reqirement'

### ISSUE THREAD

**Issue by pawansgi92** [KeshKumar/Os_Assignment#1]
Compilation failed due to following error(s). main.c: In function 'main':
main.c:21:20: error: array type has incomplete element type 'struct reqirement'
  struct reqirement s[n];
                    ^
main.c:35:3: warning: ignoring return value of 'scanf', declared with attribute warn_unused_result [-Wunused-result]
   scanf("%c%c",&ch1,&ch2);

**Comment by KeshKumar** [comment]
Can you Suggest me a Solution?

**Comment by KeshKumar** [comment]
The Issue is now resolved it was a mere spelling mistake.

**Comment by pawansgi92** [comment]
You close the issue without resolving it.
